version: '3'
services:
  db:
    image: postgres
    volumes:
        - ./backend/src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hubla
    ports:
      - "5432:5432"

